name: Build and Release

on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0 # This ensures that tags and commit history are available

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install commitizen
          pip install pyinstaller

      - name: Run build script
        run: pyinstaller --onefile --name shutdownx --add-data "requirements.txt:." --copy-metadata readchar main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shutdownx
          path: ${{ github.workspace }}/dist/shutdownx.exe # Adjust if the .exe is output elsewhere.

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            This release contains the latest build of ShutdownX.
            Download the `.exe` file below.
          artifacts: ${{ github.workspace }}/dist/shutdownx.exe
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # GitHub token to create the release
