name: Build and Release

on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    needs: bump_version # Make sure this depends on the bump version workflow completing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # This ensures that tags and commit history are available

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install commitizen

      - name: Get the new version from the bumped tag
        run: echo "VERSION=$(git tag -l | sort -V | tail -n 1)" >> $GITHUB_ENV
        # This will get the latest tag (the version bumped in bump.yml)

      - name: Run build script
        run: build.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shutdownx
          path: dist/shutdownx.exe # Adjust if the .exe is output elsewhere.

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }} # Use the version/tag from the previous step
          name: Release v${{ env.VERSION }}
          body: |
            This release contains the latest build of ShutdownX.
            Download the `.exe` file below.
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub token to create the release
