name: Build and Release

on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0 # This ensures that tags and commit history are available

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: pwsh
        run: |
          pip install -r requirements.txt
          pip install commitizen

      - name: Get the new version from Commitizen bump
        shell: pwsh
        run: |
          $version = cz version -p  # Get the project version bumped by Commitizen
          echo "New version: $version"
          echo "VERSION=$version" >> $env:GITHUB_ENV  # Set the version as an environment variable

      - name: Build the .exe file
        run: pyinstaller --onefile --clean --name shutdownx --icon=img/icon.ico --add-data "requirements.txt:." --copy-metadata readchar src/main.py

      - name: Verify .exe file exists
        run: |
          dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shutdownx
          path: ${{ github.workspace }}/dist/shutdownx.exe # Adjust if the .exe is output elsewhere.

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            This release contains the latest build of ShutdownX.
            Download the `.exe` file below.
          artifacts: ${{ github.workspace }}/dist/shutdownx.exe
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # GitHub token to create the release
