name: Run Tests

on:
  # Allow this workflow to be reusable by other workflows
  workflow_call:
    inputs: {} # Define inputs if needed for reusable workflows

  # Trigger on push to the main branch
  push:
    branches:
      - main

  # Trigger on pull requests targeting the main branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements\test.txt

      - name: Run tests and generate coverage report
        run: |
          coverage run -m pytest
          coverage report
          pylint .\src
